# Site settings
title: Mafemática- UFV
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username:  
user_description: Por que a galinha atravessoua a faixa de mobius?
user_title: Matemática + florestal + café = maf
email: luiz.h.matos@ufv.br
# twitter_username: lhenriqmatos
# github_username:  lhenriquematos
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
