# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Álgebra', folder: 'pages', file: 'facts.html'}
- {name: 'Análise', folder: 'pages', file: 'resources.html'}
- {name: 'Geometria e Topologia', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Matemática Aplicada', folder: 'pages', file: 'documentation.html'}
- {name: 'Teoria dos Números', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/Lhenriqmatos?s=08'}

- {icon: 'instagram', link: 'https://www.instagram.com/lhenriquematos/'}
- {icon: 'envelope', link: 'mailto:luiz.h.matos@ufv.br'}

# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
